work together HTML
Oleksandr-Karnaushenko/SuperPortfolioTeam pull request #6
Opened 2024-05-30 16:34 UTC by Yuliuus

added html for section "work together"

2024-05-30 19:25 UTC, Oleksandr-Karnaushenko commented on src/partials/workTogether.html
> +    <h1>Let's work together</h1>
тут точно не h1))

2024-05-30 19:25 UTC, Oleksandr-Karnaushenko requested changes
change "h"

2024-06-01 08:43 UTC, Yuliuus commented on src/partials/workTogether.html
> +    <h1>Let's work together</h1>
згодна, дякую. приступаю до роботи далі. HTML ще потребує виправленб і доповнень

2024-06-01 09:32 UTC, Oleksandr-Karnaushenko approved these changes
ok

2024-06-01 09:32 UTC, merged